### ISSUE TITLE
About thermostat state

### ISSUE THREAD

**Issue by CeccoCQ** [andrea-mattioli/bticino_x8000_component#20]
### Question

Hi Andrea,
I downloaded and installed your component correctly, great job!
I have a question related to the thermostat's state; every time I open the Thermostat card, the state is always off (probably because the state of climate.* is always set to off).
Is there a way to understand in which hvac mode it is? And if it's in boost mode, from which attribute can I get this information?

I tried setting it from the official BTicino Thermostat app, but the sensor's state (and its attributes) seems to never change.

Where am I going wrong?

**Comment by andrea-mattioli** [comment]
In this case my thermostat it's in automatic mode, the status it's active and the hvac_action it's heating:
```
hvac_modes:
  - auto
  - heat
  - cool
  - "off"
min_temp: 7
max_temp: 40
target_temp_step: 0.1
current_temperature: 17
temperature: 20
current_humidity: 65.3
hvac_action: heating
mode: automatic
status: active
current_program: At Home
available_programs:
  - Not At Home
  - At Home
friendly_name: Sala
supported_features: 385
```

In this case my thermostat it's in boost mode, and appear the hidden attribute boost_time_remainig:

```
hvac_modes:
  - auto
  - heat
  - cool
  - "off"
min_temp: 7
max_temp: 40
target_temp_step: 0.1
current_temperature: 17.2
temperature: 20
current_humidity: 65.2
hvac_action: heating
mode: boost
status: active
current_program: At Home
available_programs:
  - Not At Home
  - At Home
friendly_name: Sala
supported_features: 385
boost_time_remainig:
  days: 0
  hours: 1
  minutes: 0
  seconds: 5
```
If you are not receiving data from legrand check your c2c subscriptions via legrand api or addon configuration. The domain must be your public address and your connection must receive data from the Legrand cloud, so if you have put filters on src ip to access your network, try removing them.
